# From https://github.com/eeholmes/readthedoc-test/blob/main/.github/workflows/docs_pages.yml
name: "build docs"
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
 
      - name: Install dependencies
        run: |
          pip install "numpydoc==1.1.0" "Sphinx==5.1.0" "sphinx-book-theme" "myst_nb" "sphinx-design" "sphinxemoji" .

      - name: make the sphinx docs
        run: |
            make -C doc clean 
            sphinx-apidoc -f -o doc/source/ ../../PriorLearning
            make -C doc html

      - name: Commit changes to docs
        run: |
          cd ./gh-pages
          cp -R ../main/doc/* ./
          git config --local user.email ""
          git config --local user.name "github-actions"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "auto: Rebuild docs."
            git  push
          else
            echo No commit made because the docs have not changed.
          fi